### ISSUE TITLE
TypeError: setdefaultencoding() argument 1 must be string, not None

### ISSUE THREAD

**Issue by vlmaksime** [nkvoronov/script.pvr.favourites#1]
При запуске дополнения на Android KODI 16.1 возникает ошибка:

    -->Python callback/script returned the following error<--
     - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
    Error Type: <type 'exceptions.TypeError'>
    Error Contents: setdefaultencoding() argument 1 must be string, not None
    Traceback (most recent call last):
      File "/mnt/internal_sd/Android/data/org.xbmc.kodi/files/.kodi/addons/script.pvr.favourites/default.py", line 8, in <module>
        import action
      File "/mnt/internal_sd/Android/data/org.xbmc.kodi/files/.kodi/addons/script.pvr.favourites/resources/lib/action.py", line 12, in <module>
        import gui
      File "/mnt/internal_sd/Android/data/org.xbmc.kodi/files/.kodi/addons/script.pvr.favourites/resources/lib/gui.py", line 5, in <module>
        import common
      File "/mnt/internal_sd/Android/data/org.xbmc.kodi/files/.kodi/addons/script.pvr.favourites/resources/lib/common.py", line 30, in <module>
        sys.setdefaultencoding(encoding)
    TypeError: setdefaultencoding() argument 1 must be string, not None
    -->End of Python script error report<--

Аналогичная ошибка присутствует в дополнении 'script.epg.vsetv'

**Comment by nkvoronov** [comment]
script.pvr.favourites/resources/lib/common.py", line 29 sys.setdefaultencoding('utf-8')
sys.setdefaultencoding(encoding) нет такой строки
????
'utf-8' > None ????

Android не тестирую

**Comment by vlmaksime** [comment]
Это старая ошибка. Я закрыл проблему т.к. она давно ушла.
